# Generated by Django 3.1.3 on 2020-12-09 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='super_total',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cart',
            name='tax',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
